### ISSUE TITLE
new language: Typescript

### ISSUE THREAD

**Issue by aldy505** [teknologi-umum/flourite#5]
Test cases (just rewrite these to Typescript:
* https://rosettacode.org/wiki/Hello_world/Newbie#Javascript
* https://rosettacode.org/wiki/FizzBuzz#Javascript
* https://rosettacode.org/wiki/Sorting_algorithms/Quicksort#JavaScript
* https://rosettacode.org/wiki/HTTP#JavaScript

**Comment by Dmitryitis** [comment]
Hi, I want to help make this issue, if you do not mind

**Comment by aldy505** [comment]
@Dmitryitis sure go ahead
